#!/bin/bash
#BSUB -J petsc-test
#BSUB -q ser
#BSUB -n 1
#BSUB -e petsc.err
#BSUB -o petsc.out


module purge
module load intel/2018.4
module load mpi/intel/2018.4
module load valgrind/3.14.0

# mpirun -np 5 ./explicit.out \
# -log_view > $LSB_JOBID.log 2>&1 \

mpirun -np 1 ./explicit.out -restart 0 -n 100 \
-log_view > $LSB_JOBID.log 2>&1 \
# valgrind mpirun ./explicit.out \
# -log_view > valgrind$LSB_JOBID.log 2>&1 \

# mpirun -np 5 ./ex5.out -ksp_type gmres \
#   -ksp_gmres_restart 30 -ksp_rtol 1.0e-10 \
#   -ksp_atol 1.0e-50 -ksp_max_it 1500 \
#   -ksp_gmres_modifiedgramschmidt \
#   -pc_type asm \
#   -sub_ksp_type richardson \
#   -sub_pc_type icc -ksp_monitor_short \
#   -ksp_converged_reason \
#   -ksp_view \
#   -log_view > $LSB_JOBID.log 2>&1

